name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t integrationninjas/reactjs-app --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}'  .
      - name: Publish Image to docker hub
        run: docker push automaticorca/cinema-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull automaticorca/cinema-frontend:latest
      - name: Delete old container
        run: docker rm -f cinema-frontend-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name cinema-frontend-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' automaticorca/cinema-frontend
